リニューアルのデザイン改修
geolonia/app.geolonia.com pull request #401
Opened 2021-07-19 06:33 UTC by YasushiTakemoto

デザインを反映させましたのでご確認をお願いいたします。

![スクリーンショット 2021-07-19 15 30 23](https://user-images.githubusercontent.com/5886469/126113183-a99ac4ca-9488-4d61-beda-2997adb9f8c9.png)

2021-07-19 07:35 UTC, kamataryo commented
@YasushiTakemoto ありがとうございます！！
見やすいようにフォーマットしていただいている `'teamContent' + " " +` のような className の値なのですが、ここが Lint のルールに引っかかってしまっているみたいです..

 フォーマッタを使うか、 
``className={ `teamContent ${clsx(classes.firebase, classes.item, classes.itemCategory)}` }``

単にくっつけてもらっても大丈夫でしょうか？
`className={ 'teamContent ' + clsx(classes.firebase, classes.item, classes.itemCategory)} }`

`npm run lint` のコマンドを売っていただくと ESLint がローカルで走ります！

2021-07-19 12:37 UTC, YasushiTakemoto commented
@kamataryo @naogify ご教授ありがとうございます！
修正をしましたのでご確認お願いいたします。

2021-07-20 02:44 UTC, kamataryo approved these changes
ありがとうございます！めっちゃ素敵です！

2021-07-20 02:50 UTC, keichan34 approved these changes
お、素晴らしい！ありがとうございました。引き続き調整など適宜こういう形でPRを作ってもらったりすると非常に助かります :bow:

2021-07-20 03:00 UTC, naogify requested changes
@YasushiTakemoto 

ありがとうございます…！素敵になりました！
細かいですが、以下の箇所だけ修正お願いしても良いでしょうか…？🙏

2021-07-20 14:41 UTC, YasushiTakemoto commented
@naogify 何度もすいません、再度ご確認よろしくお願いいたします！

2021-07-21 00:51 UTC, naogify approved these changes
修正ありがとうございます！良いと思います!

2021-07-21 00:57 UTC, naogify commented
@YasushiTakemoto 
ありがとうございました…！マージしますね。

Closes #346 #347 #344 #345

2021-07-21 00:58 UTC, merged