HTML埋め込みコード生成時にAPIキーを選択可能にする
geolonia/app.geolonia.com pull request #407
Opened 2021-07-21 01:23 UTC by naogify

2021-07-21 08:01 UTC, keichan34 requested changes
修正お願いします :bow: サクッと見てるだけなのでもうちょっとあるかもしれないのですが、ひとまずこれでお願いします。
後、ローカルで実行したら変更しても Save ボタンが押せる状態にはならなかったので、そこら辺の状態管理ももう一度確認お願いします。

2021-07-21 09:03 UTC, naogify commented
@keichan34 

ありがとうございます! レビューいただいた点、修正しました。

> ローカルで実行したら変更しても Save ボタンが押せる状態にはならなかったので、そこら辺の状態管理ももう一度確認お願いします。

↑この件確認した所、自分のローカルでは Advanced Settings > アクセスを許可するの Save ボタンは押せる状態でした。もし何かエラーなど出ていたら教えて頂けますと…！

![demo](https://user-images.githubusercontent.com/8760841/126461296-a1a97825-5b73-4bbb-b773-b9b194ffce06.gif)

2021-07-21 09:16 UTC, keichan34 commented
ああ、、、なるほど。僕の勘違いかも、名前の保存ボタンを押そうとしたのかな。。

2021-07-21 09:22 UTC, keichan34 commented on src/components/Data/GeoJson/hooks/use-geojson.ts
> +  primaryApiKeyId: string | undefined;
`primaryApiKeyId?: string`

2021-07-21 09:22 UTC, keichan34 commented on src/components/Data/GeoJsonMeta.tsx
> +      throw new Error();
`throw new Error()` をするともともとのエラーが隠れてしまうんですが、なにか意図があってこういうようになってるんですか？

2021-07-21 09:22 UTC, keichan34 commented on src/components/Data/GeoJsonMeta.tsx
> +  const handleSelectApiKey = useCallback((event: React.ChangeEvent<{ value: unknown }>) => {
value: string ですかね？そうすると select にいるとタイプエラーになる感じですか？

2021-07-21 09:22 UTC, keichan34 commented on src/components/Data/GeoJsonMeta.tsx
> +        {apiKeyIdAllowedOrigins && (
ここはおそらく違う。。のかな。。？APIキーを指定していないときadvanced全体が表示されなくなってしまうと思いますが、そうすると手動で指定できなくなりますよね。。？

2021-07-21 09:22 UTC, keichan34 commented on src/components/Data/GeoJsonMeta.tsx
>                  <h5>{__("URLs from API Key page.")}</h5>
ここに、 api key が指定しないときに隠したほうが良いということでした(APIキーが選択されていないと、「URLs from API Key page」って表示する自体あまり意味がないと思って

2021-07-21 09:31 UTC, kamataryo commented on src/components/Data/GeoJsonMeta.tsx
> +          body: JSON.stringify({
@keichan34 @naogify あ、これらはサーバー側でマージされます。渡さないパラメータは更新されないです。

2021-07-21 09:35 UTC, keichan34 commented on src/components/Data/GeoJsonMeta.tsx
> +          body: JSON.stringify({
ありがとうございます！
@naogify ということで、更新されるパラメータのみ送信してください

2021-07-23 23:43 UTC, naogify commented on src/components/Data/GeoJsonMeta.tsx
> +      throw new Error();
ここ意図せず書いていたので、下のように修正しました…！

```
if (rawResp.status >= 400) {
  throw new Error(`HTTP error`);
}
```

2021-07-23 23:47 UTC, naogify commented on src/components/Data/GeoJsonMeta.tsx
> +  const handleSelectApiKey = useCallback((event: React.ChangeEvent<{ value: unknown }>) => {
はい、`value: unknown` じゃないとタイプエラーになってしまいました。。。

```
/Users/naoppy/geolonia/app.geolonia.com/src/components/Data/GeoJsonMeta.tsx
TypeScript error in /Users/naoppy/geolonia/app.geolonia.com/src/components/Data/GeoJsonMeta.tsx(493,15):
Type '(event: React.ChangeEvent<{    value: string;}>) => void' is not assignable to type '(event: ChangeEvent<{ name?: string | undefined; value: unknown; }>, child: ReactNode) => void'.
  Types of parameters 'event' and 'event' are incompatible.
    Type 'ChangeEvent<{ name?: string | undefined; value: unknown; }>' is not assignable to type 'ChangeEvent<{ value: string; }>'.
      Type '{ name?: string | undefined; value: unknown; }' is not assignable to type '{ value: string; }'.
        Types of property 'value' are incompatible.
          Type 'unknown' is not assignable to type 'string'.  TS2322

    491 |               id="api-key-select"
    492 |               value={apiKeyId || ""}
  > 493 |               onChange={handleSelectApiKey}
        |               ^
    494 |             >
    495 |               <MenuItem value="">
    496 |                 <em>None</em>
```

2021-07-24 00:01 UTC, naogify commented on src/components/Data/GeoJsonMeta.tsx
>                  <h5>{__("URLs from API Key page.")}</h5>
ありがとうございます…！確かにですね。修正しました。

2021-07-24 00:09 UTC, naogify commented
@keichan34 
ありがとうございます…！修正しました。
また連休明けに確認頂けますと…！

2021-07-24 00:10 UTC, naogify commented on src/components/Data/GeoJson/hooks/use-geojson.ts
> +  primaryApiKeyId: string | undefined;
修正しました…！

2021-07-24 00:10 UTC, naogify commented on src/components/Data/GeoJsonMeta.tsx
> +        {apiKeyIdAllowedOrigins && (
↓下で修正しました…！

2021-07-26 04:20 UTC, keichan34 approved these changes
LGTM 👍

2021-07-26 04:21 UTC, merged