GVP の処理をプログレスバーで視覚的に表示
geolonia/app.geolonia.com pull request #414
Opened 2021-07-21 14:02 UTC by kamataryo

こんな感じにしてみました。
![Jul-21-2021 23-00-12](https://user-images.githubusercontent.com/6292312/126501694-26095501-182b-4705-95c2-980273f0e17f.gif)

2021-07-24 00:32 UTC, naogify approved these changes
ありがとうございます…！LGTM👍

2021-07-26 01:54 UTC, keichan34 requested changes
確認お願いします :bow:

2021-07-26 01:54 UTC, keichan34 commented on src/components/Data/GeoJson.tsx
> +  const stepProgress = useCallback(getStepProgress, [])()
useCallbackをそのまま毎回のレンダリングで呼び出しているので、実質 `getStepProgress()` を毎回呼び出してると同じことになります。もし結果をキャッシュしたい場合は、

```
const stepProgress = useMemo(() => getStepProgress(), [])
```

で `getStepProgress()` の結果をキャッシュできます

2021-07-26 01:54 UTC, keichan34 commented on src/sleep.ts
> +};
`src/lib/sleep.ts` と `src/sleep.ts` をどっちかに統一しましょうか

2021-07-26 02:01 UTC, kamataryo commented on src/sleep.ts
> +};
あ、重複して作ってました。a01b957 で片方を削除しました。

2021-07-26 03:04 UTC, kamataryo commented on src/components/Data/GeoJson.tsx
> +  const stepProgress = useCallback(getStepProgress, [])()
こちらも修正しました。ありがとうございます！

2021-07-26 04:22 UTC, keichan34 approved these changes
ありがとうございました！ 👍

2021-07-26 04:22 UTC, merged