442 dashboard renewed notice
geolonia/app.geolonia.com pull request #460
Opened 2021-08-03 04:24 UTC by kamataryo

2021-08-03 10:26 UTC, keichan34 requested changes
🙇

2021-08-03 10:26 UTC, keichan34 commented on src/components/Dashboard.tsx
> +        {__('The dashboard has been renewed. The GeoJSON API that we used to provide is currently not accessible due to functional modifications. If you need to download the data, please <a href="htt
`golonia.com` -> `geolonia.com`

2021-08-03 10:27 UTC, kamataryo commented on src/components/Dashboard.tsx
> +        {__('The dashboard has been renewed. The GeoJSON API that we used to provide is currently not accessible due to functional modifications. If you need to download the data, please <a href="htt
ありがとうございます！
タイポ多いですね.. すみません！

2021-08-03 10:31 UTC, kamataryo commented on src/components/Dashboard.tsx
> +        {__('The dashboard has been renewed. The GeoJSON API that we used to provide is currently not accessible due to functional modifications. If you need to download the data, please <a href="htt
修正しました！

2021-08-03 10:32 UTC, keichan34 approved these changes

2021-08-04 00:29 UTC, naogify requested changes
ありがとうございます…！コメントしましたので確認お願いします。

2021-08-04 00:29 UTC, naogify commented on src/components/Dashboard.tsx
> +        <Hidden smDown>
こちらの飛行機アイコンが新しいデザインで削除になったので、削除お願いします…！
```
        <Hidden smDown>
          <div className="box-icon">
            <img src={iconPlane} alt="" className="icon" />
          </div>
        </Hidden>
```

2021-08-04 00:29 UTC, naogify commented on src/components/Dashboard.tsx
> +          'The dashboard has been renewed. The GeoJSON API that we used to provide is currently not accessible due to functional modifications. If you need to download the data, please <a href="https
こちらのリンクも `target="_blank"` の方が親切かと思いました…！

2021-08-04 00:30 UTC, kamataryo commented on src/components/Dashboard.tsx
> +        <Hidden smDown>
あら、先祖返りしてる？確認しますね。

2021-08-04 00:35 UTC, kamataryo commented on src/components/Dashboard.tsx
> +          'The dashboard has been renewed. The GeoJSON API that we used to provide is currently not accessible due to functional modifications. If you need to download the data, please <a href="https
ここなんですが、あえてつけなかったんです。
データをダウンロードをしたいと思うユーザーさんの動機って、ダッシュボードを使い続ける気持ちよりも強いもののように思います。なので、新しいウィンドウで開くことをこちらから強制する必要はない気がしました。
どう思いますか？

2021-08-04 00:38 UTC, kamataryo commented on src/components/Dashboard.tsx
> +          'The dashboard has been renewed. The GeoJSON API that we used to provide is currently not accessible due to functional modifications. If you need to download the data, please <a href="https
でも一律 target=_blank でもいいかな？

2021-08-04 00:40 UTC, naogify commented on src/components/Dashboard.tsx
> +          'The dashboard has been renewed. The GeoJSON API that we used to provide is currently not accessible due to functional modifications. If you need to download the data, please <a href="https
なるほど…！確かにデータのダウンロードしたいユーザーさんは、

データのダウンロードのお問い合わせをした時は、そのログイン時にそれ以上ダッシュボードで操作することはなさそうだから、target=_blank つけなくても良いかもしれないですね。

2021-08-04 00:42 UTC, naogify commented on src/components/Dashboard.tsx
> +          'The dashboard has been renewed. The GeoJSON API that we used to provide is currently not accessible due to functional modifications. If you need to download the data, please <a href="https
迷いますね。。。

2021-08-04 00:57 UTC, kamataryo commented on src/components/Dashboard.tsx
> +        <Hidden smDown>
こちら削除しました。ありがとうございます！

2021-08-04 01:07 UTC, kamataryo commented on src/components/Dashboard.tsx
> +          'The dashboard has been renewed. The GeoJSON API that we used to provide is currently not accessible due to functional modifications. If you need to download the data, please <a href="https
target=_blank をつけます！

2021-08-04 01:21 UTC, kamataryo commented
通知は、サイドバーに移してデザイン上の統合を図る。
@naogify よろしくお願いします！

2021-08-04 01:39 UTC, kamataryo commented on src/components/Dashboard.tsx
> +          'The dashboard has been renewed. The GeoJSON API that we used to provide is currently not accessible due to functional modifications. If you need to download the data, please <a href="https
対応しました！

2021-08-04 02:36 UTC, naogify approved these changes
@kamataryo ありがとうございます…！デザインも反映したのでマージします。

2021-08-04 02:36 UTC, merged