トップページに「Create Map」ボタンを追加
geolonia/app.geolonia.com pull request #462
Opened 2021-08-03 05:01 UTC by naogify

Closes #438

修正内容

トップページに「地図を作成する」ボタンを追加。クリックすると https://app.geolonia.com/#/api-keys に飛ぶ。

![スクリーンショット 2021-08-03 13 55 36](https://user-images.githubusercontent.com/8760841/127960072-3f6435ba-c722-4bcd-ab59-161468d39045.png)

初回（APIキー未作成）の場合は、「地図の作成にはAPIキーが必要です。「新規作成」をクリックしてAPIキーを作成してください。」を表示。

![スクリーンショット 2021-08-03 13 56 23](https://user-images.githubusercontent.com/8760841/127960213-cb1c2546-79cf-47a7-92a4-08f4444e7edd.png)

2回目からは表示なし。

![スクリーンショット 2021-08-03 13 55 57](https://user-images.githubusercontent.com/8760841/127960321-6929e412-256c-4a92-a25d-6b69f617a12d.png)

2021-08-03 05:07 UTC, naogify commented
提案して頂いてたレイアウト（https://github.com/geolonia/app.geolonia.com/issues/438#issuecomment-890847163) も検討したのですが、ドキュメントのリンクがダッシュボードに追加されたので、くどくなるかと思いこの方式にしました。

今後もっとインタラクティブにしたいですが、とりあえず木曜日を期限と考えるとこれがベターかと思いました。

@ShinichiNishikawa どうでしょうか？

2021-08-03 05:11 UTC, naogify commented
@kamataryo 

以下の箇所でタイトルのヘルパーテキストの表示を無くす変更をしたのですが、型エラーが出たので、

https://github.com/geolonia/app.geolonia.com/blob/0aacd9b7a7f153ab6830f85bef5513a0a6f42df9/src/components/Maps/APIKeys.tsx#L81

Title コンポーネントの `children` props をオプションにしました。この対応で良いか確認頂きたいです…！

https://github.com/geolonia/app.geolonia.com/blob/0aacd9b7a7f153ab6830f85bef5513a0a6f42df9/src/components/custom/Title.tsx#L16

2021-08-03 05:23 UTC, kamataryo commented
@naogify はい、影響範囲もないはずで特に問題ないと思います。

2021-08-03 05:25 UTC, kamataryo commented
関連: https://github.com/geolonia/app.geolonia.com/issues/425#issuecomment-891468985

2021-08-03 05:49 UTC, naogify commented
メモ: https://github.com/geolonia/app.geolonia.com/pull/459 のマージ後にマージ。

2021-08-03 06:53 UTC, ShinichiNishikawa commented
新しく提案されているテキストはよさそうですね。

* デザインと表示位置の初期設定ができることが分かる。

のが新しいポイントかと思いました。

一方で、今あるテキストは、

```
まずAPIキーを取得し、地図のデザインや表示位置の初期設定をしてください。
そのあと生成されたHTMLコードスニペットをあなたの Webサイトに追加すると、作成した地図が表示されます。
```

なので、

* Embed APIやポップアップなどのカスタマイズが必要なこと

が抜けていて、ユーザーの作業が完了した感じがします。
この管理画面はAPIの発行、地図のコードスニペットを作成、クレジットカードの入力ができる画面であって、ウェブサイトで地図を使うためには、ドキュメンテーションを読んでいろいろ自分でやらないといけないということが伝えたいです。

これが伝わると「ユーザーがこのサービスの利用方法を理解する」というこのブロックのゴールが達成できます。

なので、文章を増やすのでもいいですし、ビジュアルもなくしてもいいので、全体像が伝わるようにしてください。

2021-08-04 03:05 UTC, naogify commented
@ShinichiNishikawa 

> Embed APIやポップアップなどのカスタマイズが必要なこと
が抜けていて、ユーザーの作業が完了した感じがします。

Embed API や Javascript API を使うことをウェルカムボードの文章で伝えようとしたのですが、

<img width="1440" alt="スクリーンショット 2021-08-04 11 57 17" src="https://user-images.githubusercontent.com/8760841/128115498-529df649-5059-443f-a5f5-145b4ceda9f9.png">

ウェルカムボードの文量が多くなり、きちんと読んでもらえない気がするの、https://github.com/geolonia/app.geolonia.com/issues/468 で対応しようと思いました。どうでしょうか？


（文章追加した上で https://github.com/geolonia/app.geolonia.com/issues/468 対応でも良い様な気もしますが、、 ）

2021-08-04 06:08 UTC, kamataryo requested changes
@naogify 以下の確認お願いします！ 
- Learn More => 続きを読む に変更
- リンクが2箇所あるので、これは一体に。 `<CardActionArea />` というコンポーネントの中に入れる
- サポートのところは `問い合わせする` に変更

2021-08-04 07:09 UTC, naogify commented
Same as #477

2021-08-04 07:09 UTC, closed without merging