Message before inviting a user
geolonia/app.geolonia.com pull request #469
Opened 2021-08-03 07:52 UTC by keichan34

文字確認待ち

Closes #444

2021-08-03 23:40 UTC, kamataryo requested changes

2021-08-03 23:40 UTC, kamataryo commented on src/components/Team/members/invite.tsx
> +        description={sprintf(__("Please enter the email address of the person you want to invite to \"%s\". Please note that the user must create a Geolonia account first before you can send the invi
細かいですが、 サインアップURL をフォーマット変数にしてもらって `https://app.geolonia.com/#signup` または `https://app-dev.geolonia.com/#signup` で埋め込むといいかと思いました！

2021-08-03 23:40 UTC, kamataryo commented on src/components/Team/members/invite.tsx
> +        description={sprintf(__("Please enter the email address of the person you want to invite to \"%s\". Please note that the user must create a Geolonia account first before you can send the invi
あ、あとサインアップページだとこういうクエリストリングも使えます。 `https://app.geolonia.com/?lang=ja#/signup`

2021-08-04 00:10 UTC, keichan34 commented
@kamataryo リンクを追加し、直接 `#/signup` にリンク先設定しました :bow:

2021-08-04 00:18 UTC, kamataryo approved these changes
ありがとうございました！

2021-08-04 00:24 UTC, merged